name: CI
on: [push]
jobs:
  jfr-container-action-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true 
    steps:
      - name: Checkout Repositorie
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Jenkins pipeline in the container
        uses:
          jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          #pluginstxt: plugins.txt
          #jcasc: jcasc.yml